config/routes.rb
Rails.application.routes.draw do
  root to: 'blogposts#index'

  get 'blogposts/index'
  namespace :admin do
    resources :blogposts
    resources :blogpost_categories
  end
  # mount Fae below your admin namespec
  mount Fae::Engine => '/admin'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blogpost.rb
class Blogpost < ApplicationRecord
  include Fae::BaseModelConcern
  has_fae_image :main_image

  validates :title, length: { maximum: 50 }



  def fae_display_field
    title
  end

  belongs_to :blogpost_category
end

app/models/blogpost_category.rb
class BlogpostCategory < ApplicationRecord
  include Fae::BaseModelConcern

  acts_as_list add_new_at: :top
  default_scope { order(:position) }

  def fae_display_field
    name
  end

end

app/models/concerns/fae/authorization_concern.rb
module Fae
  module AuthorizationConcern
    extend ActiveSupport::Concern
    module ClassMethods

      # Use the access_map to define any controllers that need any special authorization
      # Fae comes with three default roles:
      # - super admin: CRUD all objects, INCLUDING users and root settings
      # - admin: CRUD all objects, INCLUDING users and EXCLUDING root settings
      # - users: CRUD all objects, EXCLUDING users and root settings

      # each item should have a string key of the plural controller name and
      # an array of role names for the value
      # use "content_blocks/#{page_name}" for content blocks

      # example:
      # {
      #  'people' => ['super admin', 'admin'],
      #  'content_blocks/about_us' => ['super admin']
      # }
      def access_map
        {}
      end

    end
  end
end

app/models/concerns/fae/navigation_concern.rb
module Fae
  module NavigationConcern
    extend ActiveSupport::Concern

    # define the navigation structure in this file
    # example structure:
    #
    # def structure
    #   [
    #     item('Top Nav Item 1', subitems: [
    #       item('Top Nav Dropdown Item 1', class: 'custom-class', path: some_named_route_path),
    #       item('Top Nav Dropdown Item 2', subitems: [
    #         item('Side Nav Item 1', subitems: [
    #           item('Side Nav Nested Item', path: some_named_route_path)
    #         ]),
    #         item('Side Nav Item 1', path: some_named_route_path)
    #       ]),
    #     ]),
    #     item('Pages', subitems: [
    #       item('Home', path: fae.edit_content_block_path('home')),
    #       item('About Us', path: fae.edit_content_block_path('about_us'))
    #     ])
    #   ]
    # end

    def structure
      [
        item('Blogpost Categories', path: admin_blogpost_categories_path),
        item('Blogposts', path: admin_blogposts_path),
        # scaffold inject marker
      ]
    end

  end
end

app/controllers/admin/blogpost_categories_controller.rb
module Admin
  class BlogpostCategoriesController < Fae::BaseController

  end
end

app/controllers/admin/blogposts_controller.rb
module Admin
  class BlogpostsController < Fae::BaseController

    private

    def build_assets
      @item.build_main_image if @item.main_image.blank?
    end

  end
end

app/controllers/admin/content_blocks_controller.rb
module Admin
  class ContentBlocksController < Fae::StaticPagesController

    private

    def fae_pages
      [BlogpostsPage]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogposts_controller.rb
class BlogpostsController < ApplicationController
  def index
    @blogposts = Blogpost.includes(:blogpost_category).all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogposts_helper.rb
module BlogpostsHelper
end

app/views/admin/blogpost_categories/_form.html.slim
= simple_form_for(['admin', @item]) do |f|
  == render 'fae/shared/form_header', header: @klass_name

  main.content
    = fae_input f, :name

app/views/admin/blogpost_categories/edit.html.slim
== render 'form'

app/views/admin/blogpost_categories/index.html.slim
== render 'fae/shared/index_header', title: @klass_humanized.pluralize.titleize

main.content
  table.js-sort-row
    thead
      tr
        th.th-sortable-handle
        th Name
        th.-action-wide Modified
        th.-action data-sorter="false"

    tbody
      - if @items.present?
        - @items.each do |item|
          tr id=fae_sort_id(item)
            td.sortable-handle: i.icon-sort
            td = link_to item.fae_display_field, edit_admin_blogpost_category_path(item)
            td = fae_date_format item.updated_at
            td = fae_delete_button item
      - else
        tr: td colspan="4" No items found

app/views/admin/blogpost_categories/new.html.slim
== render 'form'

app/views/admin/blogposts/_form.html.slim
= simple_form_for(['admin', @item]) do |f|
  == render 'fae/shared/form_header', header: @klass_name

  main.content
    = fae_input f, :title
    = fae_input f, :slug
    = fae_input f, :introduction, markdown: true
    = fae_input f, :body, markdown: true
    = fae_input f, :date

    = fae_association f, :blogpost_category

    = fae_image_form f, :main_image

    = f.input :keywords, collection: ['awesome', 'such', 'much', 'wow'].map { |i| [i, i] }, input_html: { multiple: true }

app/views/admin/blogposts/edit.html.slim
== render 'form'

app/views/admin/blogposts/index.html.slim
== render 'fae/shared/index_header', title: @klass_humanized.pluralize.titleize

main.content
  table.js-sort-column
    thead
      tr
        th Title
        th.-action-wide Modified
        th.-action data-sorter="false"

    tbody
      - if @items.present?
        - @items.each do |item|
          tr id=fae_sort_id(item)
            td = link_to item.fae_display_field, edit_admin_blogpost_path(item)
            td = fae_date_format item.updated_at
            td = fae_delete_button item
      - else
        tr: td colspan="3" No items found

app/views/admin/blogposts/new.html.slim
== render 'form'

app/views/blogposts/index.html.erb
<h1>Blogposts</h1>
<% @blogposts.each do |blogpost| %>
  <div>
    <h3> <%= blogpost.title %> </h3>
    <h5> <%= blogpost.blogpost_category.name %> </h5>
    <p> <%= blogpost.introduction %> </p>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CmsDemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>